version: "3"

services:
  client:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./site:/usr/share/nginx/html:ro

  healthcheck:
    test: curl --fail http://localhost || exit 1
    interval: 360s
    retries: 5
    start_period: 20s
    timeout: 10s