site_name: 124c41
nav:
    - Home: index.md
    - Conda: conda.md
    - Dataframe: dataframe.md
    - Hydra: hydra.md
    - Linux: linux.md
    - Samba: smb.md
    - MkDocs: mkdocs.md
    - scrape_pad: scrape_pad.md
    - About: about.md

theme: readthedocs