site_name: 124c41
site_description: programming, machine learning, software architecture, and more
site_author: furyhawk
copyright: Copyright 2025
plugins:
  - search
  - tags
  - awesome-pages

markdown_extensions:
  - abbr
  - attr_list

theme:
  name: material
  logo: assets/9cd3421aa95841b4b1ca45487081af9f.png
  favicon: assets/9cd3421aa95841b4b1ca45487081af9f.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference