site_name: 124c41
nav:
  - Home: index.md
  - Resume: resume.md
  - Conda: conda.md
  - venv: venv.md
  - poetry: poetry.md
  - git: git.md
  - ssh: ssh.md
  - softwarearchitecture: softwarearchitecture.md
  - vscode: code.md
  - machine_learning: machine_learning.md
  - llm: llm.md
  - embedding: embedding.md
  - llmama2: llama2.md
  - ollama: ollama.md
  - rag: rag.md
  - Framework: framework.md
  - database: db.md
  - Dataframe: dataframe.md
  - Chart: chart.md
  - anomaly_detection: anomaly_detection.md
  - Hydra: hydra.md
  - Linux: linux.md
  - macos: macos.md
  - sway: sway.md
  - Docker: docker.md
  - mqtt: mqtt.md
  - jetson: jetson.md
  - yolox: yolox.md
  - gpt: gpt.md
  - stable_diffussion: stable_diffusion.md
  - Model Analysis: wandb.md
  - Samba: smb.md
  - Samba_ubuntu: smb2.md
  - MkDocs: mkdocs.md
  - mypy: mypy.md
  - Literatures: literatures.md
  - scrape_pad: scrape_pad.md
  - nes: nes.md
  - random: random.md
  - About: about.md

theme: readthedocs
