site_name: 124c41
site_description: programming, machine learning, software architecture, and more
site_author: furyhawk
copyright: Copyright 2025
plugins:
  - search
  - tags

nav:
  - Home: index.md
  - Resume: resume.md
  - Conda: conda.md
  - venv: venv.md
  - poetry: poetry.md
  - git: git.md
  - ssh: ssh.md
  - softwarearchitecture: softwarearchitecture.md
  - vscode: code.md
  - machine_learning: machine_learning.md
  - llm: llm.md
  - embedding: embedding.md
  - llmama2: llama2.md
  - ollama: ollama.md
  - rag: rag.md
  - Framework: framework.md
  - database: db.md
  - Dataframe: dataframe.md
  - Chart: chart.md
  - anomaly_detection: anomaly_detection.md
  - Hydra: hydra.md
  - Linux: linux.md
  - Docker: docker.md
  - Kubernetes: k8s.md
  - ceph: ceph.md
  - macos: macos.md
  - sway: sway.md
  - mqtt: mqtt.md
  - jetson: jetson.md
  - yolox: yolox.md
  - gpt: gpt.md
  - stable_diffussion: stable_diffusion.md
  - Model Analysis: wandb.md
  - Samba: smb.md
  - Samba_ubuntu: smb2.md
  - MkDocs: mkdocs.md
  - mypy: mypy.md
  - Literatures: literatures.md
  - scrape_pad: scrape_pad.md
  - nes: nes.md
  - time_travel: time_travel.md
  - random: random.md
  - About: about.md

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference